pipeline 
{
    agent any

    options {
        disableConcurrentBuilds()
        skipDefaultCheckout()
    }

    triggers {
        upstream(upstreamProjects: "MyProjectSCM")
    }

    stages 
    {
        stage("Build")
        {
            lock("MyProjectSCM")
            {
                steps{
                sh '''
                    echo "Building project"
                    ls
                    g++ -isystem gcc-test/googletest/googletest/include/ -Igcc-test/googletest/googletest/ -pthread -c gcc-test/googletest/googletest/src/gtest-all.cc gcc-test/googletest/googletest/src/gtest_main.cc

                    ar -rv gcc-test/googletest/googletest/gtest_main.a gtest_main.o gtest-all.o

                    echo "Building Project"

                    mkdir gcc-test/build
                    cd gcc-test/build

                    g++ -isystem ../googletest/googletest/include/ -pthread ../Example.cpp ../test/ExampleTests.cpp ../test/ExampleTests2.cpp ../googletest/googletest/gtest_main.a -o ExampleTests
                '''
            }
            }
        }
        stage("Run Google Test")
        {
            steps{
                sh '''
                    echo "Starting google test"
                    gcc-test/build/ExampleTests --gtest_output="xml:testresults.xml"
                '''
            }
        }
    }
    post 
    {
        always {
            archiveArtifacts 'testresults.xml'
            cleanWs()
        }
        failure {
            archiveArtifacts 'testresults.xml'
        }
    }
}