pipeline 
{
    agent any

    options {
        disableConcurrentBuilds()
        skipDefaultCheckout()
    }

    triggers { upstream(upstreamProjects: 'MyProjectSCM', threshold: hudson.model.Result.SUCCESS) }

    stages 
    {
        stage("Build")
        {
            steps
            {
                lock('MyProjectSCM') 
                {
                
                sh '''
                echo "Building CMake Project"

                '''
                cmakeBuild buildDir: '../MyProjectSCM/cmake-test/build', buildType: 'Debug', cleanBuild: true, generator: 'Unix Makefiles', installation: 'InSearchPath', sourceDir: '../MyProjectSCM/cmake-test'

                sh '''
                ls 
                cd ../MyProjectSCM/cmake-test/build 
                make
                '''
                
            }
            }
        }
        stage("Run Google Test")
        {
            steps{
                sh '''
                    echo "Starting google test"
                    cd ../MyProjectSCM/cmake-test/build/test
                    ./UnitTests --gtest_output="xml:testresults.xml"
                '''
            }
        }
    }
}